### ISSUE TITLE
Sort by Location of User

### ISSUE THREAD

**Issue by andyparkerson** [LouisianaGroups/louisiana-groups#60]
grab the visitor's IP address and have it automatically sort by the city they're in.

**Comment by adamculpepper** [comment]
Thanks for the suggestion @andyparkerson! I started working on the first steps of this as you can see inside the on.('change') of the `scripts.js` file. I was planning on using `history.pushState` to update the URL address when the location was changed, but ran into some issues with loading that address when you first go to that url, for example http://louisianagroups.com/baton-rouge. I wasn't happy with the site fully loading and then the locations dropdown kicking in to filter them. I want them to load like normal, already filtered. I needed to refactor the promises (which I ended up using Knockout Subscriptions instead) and needed to move on to more core functionality.

But this update is very high on my mental todo list and thank you for documenting it. :)

**Comment by adamculpepper** [comment]
@andyparkerson this is pushed to the live site. It took quite a bit of doing!

I ended up writing a custom jQuery plugin in the process because I kept fighting with Select2's dropdown position (when the select2 element was hidden).

I started off using http://ip-api.com/json for user location detection but found out that they don't allow HTTPS for free, so I went down the route of using Google's Geocoding Location API but there were too many hurtles to jump over and the looming monthly API charge based on calls, so I ended up going with https://extreme-ip-lookup.com/json since it's free up to 50,000/month and gives HTTPS access. If we ever end up getting over 50,000 unique visits to the site, we'll have to refactor this piece, but I HIGHLY doubt that'll ever happen, but a girl can dream!

I added issue #67 as a measure to make sure we aren't doing needless location detection API calls in the future.
