### ISSUE TITLE
Use localStorage for storing the user City + State to minimize location detection API calls

### ISSUE THREAD

**Issue by adamculpepper** [LouisianaGroups/louisiana-groups#67]

**Comment by andyparkerson** [comment]
I'm always surprised more people don't use localStorage more often. My only worry with that (concern, really) is that I am currently using the new Chromium Edge, and whenever it upgrades (which is all the time) many of my websites forget who I am. I'm not sure if it's a lost cookie or cleaned out localStorage.

Another option would be to couple the localStorage with saving the api call results. I think you had an issue open for using some sort of db instead of the google sheet. That could be used to store and retrieve IPs and their locations. BBQGuys is currently doing this in the address autocomplete in checkout.

It would probably be interesting to look at the server logs and see how many unique visitors (unique IPs) the site had, to gauge how important this optimization is. No sense trying to get 5 more horsepower out of an engine if one of the tires is flat. But sometimes tuning an engine is more fun than patching a tire.

**Comment by adamculpepper** [comment]
Thanks for the concern, and I agree! I've been wanting to use localStorage in one of my projects for a long long time and this is the first chance I've been able to justify it. The reason you described is a great example of why I generally use cookies over localStorage unfortunatly. I think using localStorage for this enhancement (to cut down on the amount of hits to the location detection API) is a great use of localStorage, so I went with it.

That said - this issue is complete. The location detection API only gets called if the localStorage data isn't already there, cutting down quite a bit on the number of requests the API should be hit.

Yea, we talked about using a cloud DB solution, but in this MVP phase/mode we're in, I think Google Sheets works perfectly for our needs. Especially since we're dumping directly into the Google Sheet via the Sheets API not (similar to using a Google Form and dumping the results into Google Sheets and using that result data for the DB).
